services:
  dev:
    container_name: tdt4186
    volumes:
      - .:/xv6
    command: bash -c "make qemu"
    build:
      context: .
      dockerfile: docker/Dockerfile
    cap_add:
      - SYS_PTRACE
    tty: true
    stdin_open: true
  debug:
    container_name: tdt4186
    volumes:
      - .:/xv6
    ports:
      - 25001:25001
    command: bash -c "make qemu-gdb"
    build:
      context: .
      dockerfile: docker/Dockerfile
    cap_add:
      - SYS_PTRACE
    tty: true
    stdin_open: true